"""Tests for nudge receipt tracking and autopsy engine."""
from __future__ import annotations
import json
import os
import sqlite3
import tempfile
from pathlib import Path

import pytest

# Patch HERMES_HOME before importing the module
_tmp = tempfile.mkdtemp()
os.environ["HERMES_HOME"] = _tmp
os.environ["HERMES_REPO"] = _tmp

from plugins.personal_ops import nudge_receipts


@pytest.fixture(autouse=True)
def _isolate(tmp_path, monkeypatch):
    """Isolate each test with a fresh DB and regression test path."""
    monkeypatch.setattr(nudge_receipts, "DB_PATH", tmp_path / "po" / "event_log.db")
    monkeypatch.setattr(
        nudge_receipts,
        "REGRESSION_TESTS_PATH",
        tmp_path / "tests" / "autogenerated_regression_test.py",
    )
    monkeypatch.setattr(
        nudge_receipts,
        "BAD_NUDGE_PROPOSALS_PATH",
        tmp_path / "po" / "bad_nudge_regression_proposals.jsonl",
    )


class TestLogNudgeReceipt:
    def test_creates_receipt_and_returns_id(self):
        rid = nudge_receipts.log_nudge_receipt(
            event_type="coaching_nudge",
            task_id="t1",
            task_content="Morning Launch",
            trigger="sticky_procrastination",
            assumptions={"avoidance_score": 0.7},
            buttons=["Start sprint", "Too late", "Bad nudge"],
        )
        assert rid
        receipts = nudge_receipts.get_recent_receipts(limit=10)
        assert len(receipts) == 1
        assert receipts[0]["id"] == rid
        assert receipts[0]["outcome"] == "pending"

    def test_multiple_receipts_ordered_newest_first(self):
        rid1 = nudge_receipts.log_nudge_receipt(
            event_type="event_a", task_content="Alpha"
        )
        rid2 = nudge_receipts.log_nudge_receipt(
            event_type="event_b", task_content="Beta"
        )
        receipts = nudge_receipts.get_recent_receipts()
        assert receipts[0]["id"] == rid2
        assert receipts[1]["id"] == rid1

    def test_telegram_dispatch_signature_logs_receipt(self):
        rid = nudge_receipts.log_nudge_receipt(
            chat_id=123,
            message_id=456,
            text="Laundry is still open.",
            message_class="execution_nudge",
            source="telegram",
            buttons=[["Done", "Bad nudge"]],
            metadata={"nudge_score": 0.73},
        )

        receipts = nudge_receipts.get_recent_receipts(limit=10)
        assert receipts[0]["id"] == rid
        assert receipts[0]["event_type"] == "execution_nudge"
        assert receipts[0]["task_content"] == "Laundry is still open."
        assert receipts[0]["telegram_message_id"] == "456"


class TestRecordOutcome:
    def test_valid_outcome_updates(self):
        rid = nudge_receipts.log_nudge_receipt(
            event_type="nudge", task_content="Plan outing"
        )
        ok = nudge_receipts.record_outcome(rid, "start_sprint")
        assert ok is True
        receipts = nudge_receipts.get_recent_receipts()
        assert receipts[0]["outcome"] == "start_sprint"

    def test_invalid_outcome_rejected(self):
        rid = nudge_receipts.log_nudge_receipt(
            event_type="nudge", task_content="Plan outing"
        )
        ok = nudge_receipts.record_outcome(rid, "invalid_outcome")
        assert ok is False

    def test_missing_receipt_returns_false(self):
        ok = nudge_receipts.record_outcome("nonexistent-id", "too_late")
        assert ok is False

    def test_callback_signature_records_feedback_by_message_id(self):
        nudge_receipts.log_nudge_receipt(
            chat_id=123,
            message_id=456,
            text="Laundry is still open.",
            message_class="execution_nudge",
            source="telegram",
            buttons=["Done", "Bad nudge"],
        )

        ok = nudge_receipts.record_outcome(
            callback_data="hermes_feedback:bad_nudge",
            chat_id=123,
            message_id=456,
            user_id=789,
            metadata={"handler": "telegram._handle_callback_query"},
        )

        receipts = nudge_receipts.get_recent_receipts(limit=10)
        assert ok is True
        assert receipts[0]["outcome"] == "bad_nudge"


class TestAutopsy:
    def test_autopsy_records_and_writes_regression_proposal(self, tmp_path):
        rid = nudge_receipts.log_nudge_receipt(
            event_type="coaching_nudge",
            task_id="t42",
            task_content="Transition into family time",
            trigger="avoidance_detected",
            assumptions={"hour": 7, "presence": "desk", "day_phase": "morning"},
        )
        nudge_receipts.record_outcome(rid, "bad_nudge")

        result = nudge_receipts.record_autopsy(
            rid,
            reason="too_late",
            notes="It was 7 AM, this is an evening task",
        )

        assert result.get("reason") == "too_late"
        assert result["original"]["task_content"] == "Transition into family time"
        assert result["original"]["assumptions"]["hour"] == 7

        # Verify the autopsy was persisted
        receipts = nudge_receipts.get_recent_receipts()
        assert receipts[0]["autopsy"]["reason"] == "too_late"

        # Verify a proposal was generated without mutating repository tests.
        assert not nudge_receipts.REGRESSION_TESTS_PATH.exists()
        proposal_path = nudge_receipts.BAD_NUDGE_PROPOSALS_PATH
        assert proposal_path.exists()
        proposal = json.loads(proposal_path.read_text(encoding="utf-8").splitlines()[-1])
        assert proposal["reason"] == "too_late"
        assert proposal["task_content"] == "Transition into family time"

    def test_autopsy_nonexistent_receipt(self):
        result = nudge_receipts.record_autopsy(
            "does-not-exist",
            reason="wrong_context",
        )
        assert result.get("error") == "receipt_not_found"


class TestBadNudgeStats:
    def test_stats_with_no_data(self):
        stats = nudge_receipts.get_bad_nudge_stats()
        assert stats["total_nudges"] == 0
        assert stats["bad_nudges"] == 0
        assert stats["bad_rate"] == 0.0

    def test_stats_reflect_bad_nudges(self):
        rid1 = nudge_receipts.log_nudge_receipt(
            event_type="nudge", task_content="Task A"
        )
        rid2 = nudge_receipts.log_nudge_receipt(
            event_type="nudge", task_content="Task B"
        )
        rid3 = nudge_receipts.log_nudge_receipt(
            event_type="nudge", task_content="Task C"
        )
        nudge_receipts.record_outcome(rid1, "start_sprint")
        nudge_receipts.record_autopsy(rid2, reason="wrong_context")
        nudge_receipts.record_autopsy(rid3, reason="too_late")

        stats = nudge_receipts.get_bad_nudge_stats()
        assert stats["total_nudges"] == 3
        assert stats["bad_nudges"] == 2
        assert stats["reason_breakdown"]["wrong_context"] == 1
        assert stats["reason_breakdown"]["too_late"] == 1
