"""Hermes nudge receipt and bad-nudge proposal tracking."""
from __future__ import annotations

import hashlib
import json
import os
import sqlite3
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

HERMES_HOME = Path(os.getenv("HERMES_HOME", str(Path.home() / ".hermes")))
DB_PATH = HERMES_HOME / "personal_ops" / "event_log.db"

# Kept for backward compatibility with old tests/config, but runtime no longer
# mutates repository tests directly.
REGRESSION_TESTS_PATH = (
    Path(os.getenv("HERMES_REPO", str(Path.home() / "hermes-agent")))
    / "tests"
    / "autogenerated_regression_test.py"
)
BAD_NUDGE_PROPOSALS_PATH = HERMES_HOME / "personal_ops" / "bad_nudge_regression_proposals.jsonl"


def _ensure_tables() -> None:
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(DB_PATH, timeout=5.0)
    cur = conn.cursor()
    cur.execute("PRAGMA busy_timeout=5000")
    cur.execute(
        """
        CREATE TABLE IF NOT EXISTS nudge_receipts (
            id TEXT PRIMARY KEY,
            created_at TEXT NOT NULL,
            event_type TEXT NOT NULL,
            task_id TEXT,
            task_content TEXT,
            trigger TEXT,
            assumptions TEXT,
            buttons TEXT,
            telegram_message_id TEXT,
            outcome TEXT DEFAULT 'pending',
            outcome_ts TEXT,
            autopsy TEXT
        )
        """
    )
    cur.execute("PRAGMA table_info(nudge_receipts)")
    columns = {row[1] for row in cur.fetchall()}
    for name, ddl in {
        "chat_id": "TEXT",
        "message_id": "TEXT",
        "text": "TEXT",
        "message_class": "TEXT",
        "source": "TEXT",
        "metadata": "TEXT",
        "callback_data": "TEXT",
    }.items():
        if name not in columns:
            cur.execute(f"ALTER TABLE nudge_receipts ADD COLUMN {name} {ddl}")
    cur.execute("CREATE INDEX IF NOT EXISTS idx_nudge_receipts_message_id ON nudge_receipts(message_id)")
    cur.execute("CREATE INDEX IF NOT EXISTS idx_nudge_receipts_telegram_message_id ON nudge_receipts(telegram_message_id)")
    cur.execute("CREATE INDEX IF NOT EXISTS idx_nudge_receipts_outcome ON nudge_receipts(outcome)")
    conn.commit()
    conn.close()


def _json_or_none(value: Any) -> Optional[str]:
    return json.dumps(value) if value is not None else None


def log_nudge_receipt(
    *,
    event_type: Optional[str] = None,
    task_id: Optional[str] = None,
    task_content: Optional[str] = None,
    trigger: Optional[str] = None,
    assumptions: Optional[Dict[str, Any]] = None,
    buttons: Optional[Any] = None,
    telegram_message_id: Optional[Any] = None,
    chat_id: Optional[Any] = None,
    message_id: Optional[Any] = None,
    text: Optional[str] = None,
    message_class: Optional[str] = None,
    source: Optional[str] = None,
    metadata: Optional[Dict[str, Any]] = None,
) -> str:
    """Log a nudge dispatch and return the receipt ID.

    Supports both the older event/task-shaped API and the Telegram dispatch API.
    """
    _ensure_tables()
    receipt_id = str(uuid.uuid4())
    now = datetime.now(timezone.utc).isoformat()
    resolved_event_type = event_type or message_class or "telegram_message"
    resolved_task_content = task_content if task_content is not None else text
    resolved_message_id = telegram_message_id if telegram_message_id is not None else message_id
    resolved_message_id_s = str(resolved_message_id) if resolved_message_id is not None else None
    chat_id_s = str(chat_id) if chat_id is not None else None
    conn = sqlite3.connect(DB_PATH, timeout=5.0)
    cur = conn.cursor()
    cur.execute("PRAGMA busy_timeout=5000")
    cur.execute(
        """
        INSERT INTO nudge_receipts
            (id, created_at, event_type, task_id, task_content, trigger,
             assumptions, buttons, telegram_message_id, chat_id, message_id,
             text, message_class, source, metadata)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        (
            receipt_id,
            now,
            resolved_event_type,
            task_id,
            resolved_task_content,
            trigger,
            _json_or_none(assumptions),
            _json_or_none(buttons),
            resolved_message_id_s,
            chat_id_s,
            resolved_message_id_s,
            text,
            message_class,
            source,
            _json_or_none(metadata),
        ),
    )
    conn.commit()
    conn.close()
    return receipt_id


VALID_OUTCOMES = {
    "acknowledged",
    "archived",
    "bad_nudge",
    "blocked",
    "defer_30m",
    "defer_tomorrow",
    "deleted",
    "done",
    "draft_tomorrow",
    "handled",
    "not_home",
    "schedule_next_window",
    "snoozed",
    "start_sprint",
    "too_late",
}


def _outcome_from_callback(callback_data: str) -> str:
    data = str(callback_data or "").strip()
    if data.startswith("hermes_feedback:"):
        return data.split(":", 1)[1].strip().lower() or "acknowledged"
    if data.startswith("po:task_complete:"):
        return "done"
    if data.startswith("po:gym:complete:"):
        return "done"
    if data.startswith("po:gym:partial:"):
        return "handled"
    if data.startswith("po:gym:mistake"):
        return "bad_nudge"
    if data.startswith("po:task_defer:"):
        return "defer_tomorrow"
    if data.startswith("po:task_delete:"):
        return "archived"
    if data.startswith("po:nudge_mute:"):
        return "snoozed"
    if data.startswith("po:sprint:"):
        return "start_sprint"
    return "acknowledged"


def record_outcome(
    receipt_id: Optional[str] = None,
    outcome: Optional[str] = None,
    *,
    callback_data: Optional[str] = None,
    chat_id: Optional[Any] = None,
    message_id: Optional[Any] = None,
    user_id: Optional[Any] = None,
    metadata: Optional[Dict[str, Any]] = None,
) -> bool:
    """Update the outcome of a nudge receipt. Returns True on success."""
    _ensure_tables()
    if callback_data is not None:
        outcome = _outcome_from_callback(callback_data)
    if outcome not in VALID_OUTCOMES:
        return False

    conn = sqlite3.connect(DB_PATH, timeout=5.0)
    cur = conn.cursor()
    cur.execute("PRAGMA busy_timeout=5000")
    target_id = receipt_id
    if not target_id and message_id is not None:
        msg = str(message_id)
        params: List[Any] = [msg, msg]
        where = "(message_id = ? OR telegram_message_id = ?)"
        if chat_id is not None:
            where += " AND chat_id = ?"
            params.append(str(chat_id))
        cur.execute(
            f"SELECT id FROM nudge_receipts WHERE {where} ORDER BY created_at DESC LIMIT 1",
            params,
        )
        row = cur.fetchone()
        target_id = row[0] if row else None
    if not target_id:
        conn.close()
        return False

    now = datetime.now(timezone.utc).isoformat()
    merged_metadata = dict(metadata or {})
    if user_id is not None:
        merged_metadata["user_id"] = str(user_id)
    cur.execute(
        """
        UPDATE nudge_receipts
        SET outcome = ?, outcome_ts = ?, callback_data = ?, metadata = ?
        WHERE id = ?
        """,
        (
            outcome,
            now,
            callback_data,
            _json_or_none(merged_metadata),
            target_id,
        ),
    )
    changed = cur.rowcount > 0
    conn.commit()
    conn.close()
    return changed


AUTOPSY_REASONS = [
    "too_late",
    "wrong_context",
    "vague",
    "duplicate",
    "irrelevant",
]


def record_autopsy(
    receipt_id: str,
    *,
    reason: str,
    notes: Optional[str] = None,
) -> Dict[str, Any]:
    """Run an autopsy on a bad nudge and persist a reviewed-test proposal."""
    _ensure_tables()
    autopsy_data = {
        "reason": reason,
        "notes": notes,
        "recorded_at": datetime.now(timezone.utc).isoformat(),
    }
    conn = sqlite3.connect(DB_PATH, timeout=5.0)
    cur = conn.cursor()
    cur.execute(
        "SELECT event_type, task_id, task_content, trigger, assumptions FROM nudge_receipts WHERE id = ?",
        (receipt_id,),
    )
    row = cur.fetchone()
    if not row:
        conn.close()
        return {"error": "receipt_not_found"}

    autopsy_data["original"] = {
        "event_type": row[0],
        "task_id": row[1],
        "task_content": row[2],
        "trigger": row[3],
        "assumptions": json.loads(row[4]) if row[4] else None,
    }
    cur.execute(
        "UPDATE nudge_receipts SET autopsy = ?, outcome = 'bad_nudge' WHERE id = ?",
        (json.dumps(autopsy_data), receipt_id),
    )
    conn.commit()
    conn.close()
    _write_regression_proposal(receipt_id, autopsy_data)
    return autopsy_data


def _write_regression_proposal(receipt_id: str, autopsy: Dict[str, Any]) -> None:
    original = autopsy.get("original", {})
    proposal = {
        "proposal_id": "bad_nudge_" + hashlib.sha256(receipt_id.encode("utf-8")).hexdigest()[:12],
        "receipt_id": receipt_id,
        "created_at": datetime.now(timezone.utc).isoformat(),
        "kind": "bad_nudge_regression_proposal",
        "reason": autopsy.get("reason", "unknown"),
        "notes": autopsy.get("notes"),
        "task_content": original.get("task_content", "unknown_task"),
        "event_type": original.get("event_type", "unknown_event"),
        "assumptions": original.get("assumptions") or {},
        "expected_behavior": "Create a reviewed regression test that blocks this nudge in the same context.",
    }
    BAD_NUDGE_PROPOSALS_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(BAD_NUDGE_PROPOSALS_PATH, "a", encoding="utf-8") as f:
        f.write(json.dumps(proposal, sort_keys=True) + "\n")


def get_recent_receipts(limit: int = 20) -> List[Dict[str, Any]]:
    """Return recent nudge receipts, newest first."""
    _ensure_tables()
    conn = sqlite3.connect(DB_PATH, timeout=5.0)
    cur = conn.cursor()
    cur.execute(
        """
        SELECT id, created_at, event_type, task_id, task_content, trigger,
               outcome, autopsy, telegram_message_id
        FROM nudge_receipts
        ORDER BY created_at DESC
        LIMIT ?
        """,
        (limit,),
    )
    rows = cur.fetchall()
    conn.close()
    return [
        {
            "id": row[0],
            "created_at": row[1],
            "event_type": row[2],
            "task_id": row[3],
            "task_content": row[4],
            "trigger": row[5],
            "outcome": row[6],
            "autopsy": json.loads(row[7]) if row[7] else None,
            "telegram_message_id": row[8],
        }
        for row in rows
    ]


def get_bad_nudge_stats() -> Dict[str, Any]:
    """Return aggregate statistics on bad nudges."""
    _ensure_tables()
    conn = sqlite3.connect(DB_PATH, timeout=5.0)
    cur = conn.cursor()
    cur.execute("SELECT COUNT(*) FROM nudge_receipts")
    total = cur.fetchone()[0]
    cur.execute("SELECT COUNT(*) FROM nudge_receipts WHERE outcome = 'bad_nudge'")
    bad = cur.fetchone()[0]
    cur.execute("SELECT autopsy FROM nudge_receipts WHERE outcome = 'bad_nudge' AND autopsy IS NOT NULL")
    reason_counts: Dict[str, int] = {}
    for (autopsy_json,) in cur.fetchall():
        try:
            data = json.loads(autopsy_json)
            reason = data.get("reason", "unknown")
            reason_counts[reason] = reason_counts.get(reason, 0) + 1
        except Exception:
            pass
    conn.close()
    return {
        "total_nudges": total,
        "bad_nudges": bad,
        "bad_rate": bad / max(1, total),
        "reason_breakdown": reason_counts,
    }
