"""Hermes Nudge Receipt Tracker & Autopsy Engine.

Logs a receipt for every nudge dispatched to Telegram, tracks button outcomes,
runs structured autopsies on 'Bad Nudge' reports, and auto-generates regression
test cases to prevent repeating the same mistake.
"""
from __future__ import annotations
import json
import os
import sqlite3
import time
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

HERMES_HOME = Path(os.getenv("HERMES_HOME", str(Path.home() / ".hermes")))
DB_PATH = HERMES_HOME / "personal_ops" / "event_log.db"
REGRESSION_TESTS_PATH = (
    Path(os.getenv("HERMES_REPO", str(Path.home() / "hermes-agent")))
    / "tests"
    / "autogenerated_regression_test.py"
)

# ---------------------------------------------------------------------------
# DB helpers
# ---------------------------------------------------------------------------
def _ensure_tables() -> None:
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(DB_PATH)
    cur = conn.cursor()
    cur.execute(
        """
        CREATE TABLE IF NOT EXISTS nudge_receipts (
            id TEXT PRIMARY KEY,
            created_at TEXT NOT NULL,
            event_type TEXT NOT NULL,
            task_id TEXT,
            task_content TEXT,
            trigger TEXT,
            assumptions TEXT,
            buttons TEXT,
            telegram_message_id TEXT,
            outcome TEXT DEFAULT 'pending',
            outcome_ts TEXT,
            autopsy TEXT
        )
        """
    )
    conn.commit()
    conn.close()


# ---------------------------------------------------------------------------
# Receipt logging
# ---------------------------------------------------------------------------
def log_nudge_receipt(
    *,
    event_type: str,
    task_id: Optional[str] = None,
    task_content: Optional[str] = None,
    trigger: Optional[str] = None,
    assumptions: Optional[Dict[str, Any]] = None,
    buttons: Optional[List[str]] = None,
    telegram_message_id: Optional[str] = None,
) -> str:
    """Log a nudge dispatch and return the receipt ID."""
    _ensure_tables()
    receipt_id = str(uuid.uuid4())
    now = datetime.now(timezone.utc).isoformat()
    conn = sqlite3.connect(DB_PATH)
    cur = conn.cursor()
    cur.execute(
        """
        INSERT INTO nudge_receipts
            (id, created_at, event_type, task_id, task_content, trigger,
             assumptions, buttons, telegram_message_id)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        (
            receipt_id,
            now,
            event_type,
            task_id,
            task_content,
            trigger,
            json.dumps(assumptions) if assumptions else None,
            json.dumps(buttons) if buttons else None,
            telegram_message_id,
        ),
    )
    conn.commit()
    conn.close()
    return receipt_id


# ---------------------------------------------------------------------------
# Outcome recording
# ---------------------------------------------------------------------------
VALID_OUTCOMES = {"start_sprint", "too_late", "not_home", "bad_nudge", "snoozed", "acknowledged"}

def record_outcome(receipt_id: str, outcome: str) -> bool:
    """Update the outcome of a nudge receipt. Returns True on success."""
    _ensure_tables()
    if outcome not in VALID_OUTCOMES:
        return False
    now = datetime.now(timezone.utc).isoformat()
    conn = sqlite3.connect(DB_PATH)
    cur = conn.cursor()
    cur.execute(
        "UPDATE nudge_receipts SET outcome = ?, outcome_ts = ? WHERE id = ?",
        (outcome, now, receipt_id),
    )
    changed = cur.rowcount > 0
    conn.commit()
    conn.close()
    return changed


# ---------------------------------------------------------------------------
# Autopsy system
# ---------------------------------------------------------------------------
AUTOPSY_REASONS = [
    "too_late",       # Nudge arrived after the window closed
    "wrong_context",  # User was in a different location / mode
    "vague",          # Task itself is vague / not actionable
    "duplicate",      # Already doing this or just finished it
    "irrelevant",     # Task is not relevant right now
]

def record_autopsy(
    receipt_id: str,
    *,
    reason: str,
    notes: Optional[str] = None,
) -> Dict[str, Any]:
    """Run an autopsy on a bad nudge and persist it."""
    _ensure_tables()
    autopsy_data = {
        "reason": reason,
        "notes": notes,
        "recorded_at": datetime.now(timezone.utc).isoformat(),
    }
    conn = sqlite3.connect(DB_PATH)
    cur = conn.cursor()
    # Fetch the original receipt for context
    cur.execute(
        "SELECT event_type, task_id, task_content, trigger, assumptions FROM nudge_receipts WHERE id = ?",
        (receipt_id,),
    )
    row = cur.fetchone()
    if not row:
        conn.close()
        return {"error": "receipt_not_found"}

    autopsy_data["original"] = {
        "event_type": row[0],
        "task_id": row[1],
        "task_content": row[2],
        "trigger": row[3],
        "assumptions": json.loads(row[4]) if row[4] else None,
    }

    cur.execute(
        "UPDATE nudge_receipts SET autopsy = ?, outcome = 'bad_nudge' WHERE id = ?",
        (json.dumps(autopsy_data), receipt_id),
    )
    conn.commit()
    conn.close()

    # Generate regression test
    _generate_regression_test(receipt_id, autopsy_data)

    return autopsy_data


# ---------------------------------------------------------------------------
# Regression test generator
# ---------------------------------------------------------------------------
def _generate_regression_test(receipt_id: str, autopsy: Dict[str, Any]) -> None:
    """Append a test case to the autogenerated regression test file."""
    original = autopsy.get("original", {})
    reason = autopsy.get("reason", "unknown")
    task_content = original.get("task_content", "unknown_task")
    event_type = original.get("event_type", "unknown_event")
    assumptions = original.get("assumptions") or {}

    # Sanitize the task content to make a valid function name
    safe_name = "".join(
        ch if ch.isalnum() else "_" for ch in str(task_content)[:40]
    ).strip("_").lower()
    func_name = f"test_regression_{safe_name}_{receipt_id[:8]}"

    test_code = f'''

def {func_name}():
    """Auto-generated regression test from bad-nudge autopsy.
    
    Receipt: {receipt_id}
    Reason:  {reason}
    Notes:   {autopsy.get("notes", "none")}
    Task:    {task_content}
    Event:   {event_type}
    """
    # This nudge was flagged as bad because: {reason}
    # The system should NOT fire event_type="{event_type}" for task "{task_content}"
    # under the conditions captured in assumptions: {json.dumps(assumptions)}
    assumptions = {json.dumps(assumptions)}
    assert assumptions is not None, "Assumptions must be recorded for regression"
    # TODO: Add specific assertion based on the autopsy reason
    # For reason={reason}, verify the decision daemon would NOT fire this nudge
'''

    REGRESSION_TESTS_PATH.parent.mkdir(parents=True, exist_ok=True)

    # Write header if file does not exist
    if not REGRESSION_TESTS_PATH.exists():
        header = '''"""Auto-generated regression tests from Hermes bad-nudge autopsies.

DO NOT EDIT MANUALLY — these tests are appended automatically when a user
flags a nudge as bad and completes an autopsy.
"""
import pytest
'''
        REGRESSION_TESTS_PATH.write_text(header, encoding="utf-8")

    with open(REGRESSION_TESTS_PATH, "a", encoding="utf-8") as f:
        f.write(test_code)


# ---------------------------------------------------------------------------
# Query helpers
# ---------------------------------------------------------------------------
def get_recent_receipts(limit: int = 20) -> List[Dict[str, Any]]:
    """Return recent nudge receipts, newest first."""
    _ensure_tables()
    conn = sqlite3.connect(DB_PATH)
    cur = conn.cursor()
    cur.execute(
        "SELECT id, created_at, event_type, task_id, task_content, trigger, outcome, autopsy "
        "FROM nudge_receipts ORDER BY created_at DESC LIMIT ?",
        (limit,),
    )
    rows = cur.fetchall()
    conn.close()
    results = []
    for row in rows:
        entry = {
            "id": row[0],
            "created_at": row[1],
            "event_type": row[2],
            "task_id": row[3],
            "task_content": row[4],
            "trigger": row[5],
            "outcome": row[6],
            "autopsy": json.loads(row[7]) if row[7] else None,
        }
        results.append(entry)
    return results


def get_bad_nudge_stats() -> Dict[str, Any]:
    """Return aggregate statistics on bad nudges."""
    _ensure_tables()
    conn = sqlite3.connect(DB_PATH)
    cur = conn.cursor()
    cur.execute("SELECT COUNT(*) FROM nudge_receipts")
    total = cur.fetchone()[0]
    cur.execute("SELECT COUNT(*) FROM nudge_receipts WHERE outcome = 'bad_nudge'")
    bad = cur.fetchone()[0]
    cur.execute("SELECT autopsy FROM nudge_receipts WHERE outcome = 'bad_nudge' AND autopsy IS NOT NULL")
    reason_counts: Dict[str, int] = {}
    for (autopsy_json,) in cur.fetchall():
        try:
            data = json.loads(autopsy_json)
            reason = data.get("reason", "unknown")
            reason_counts[reason] = reason_counts.get(reason, 0) + 1
        except Exception:
            pass
    conn.close()
    return {
        "total_nudges": total,
        "bad_nudges": bad,
        "bad_rate": bad / max(1, total),
        "reason_breakdown": reason_counts,
    }
